name: VegaLeaderboards
main: SVega9848\VegaLeaderboards\Loader
version: 1.0.0
api: [4.0.0]
author: SVega9848
description: Display leaderboards in your server!

permissions:
  vegaleaderboards.cmd:
    description: Leaderboards!
    default: op
